rule win_vidar_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2020-12-22"
        version = "1"
        description = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vidar"
        malpedia_rule_date = "20201222"
        malpedia_hash = "30354d830a29f0fbd3714d93d94dea941d77a130"
        malpedia_version = "20201023"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { e8???????? 59 83f8ff 7503 32c0 c3 8b4c2404 }
            // n = 7, score = 1700
            //   e8????????           |                     
            //   59                   | pop                 ecx
            //   83f8ff               | cmp                 eax, -1
            //   7503                 | jne                 5
            //   32c0                 | xor                 al, al
            //   c3                   | ret                 
            //   8b4c2404             | mov                 ecx, dword ptr [esp + 4]

        $sequence_1 = { 8b742408 8b06 8b4804 6a0a }
            // n = 4, score = 1700
            //   8b742408             | mov                 esi, dword ptr [esp + 8]
            //   8b06                 | mov                 eax, dword ptr [esi]
            //   8b4804               | mov                 ecx, dword ptr [eax + 4]
            //   6a0a                 | push                0xa

        $sequence_2 = { c9 c3 8b542408 85d2 7503 33c0 c3 }
            // n = 7, score = 1700
            //   c9                   | leave               
            //   c3                   | ret                 
            //   8b542408             | mov                 edx, dword ptr [esp + 8]
            //   85d2                 | test                edx, edx
            //   7503                 | jne                 5
            //   33c0                 | xor                 eax, eax
            //   c3                   | ret                 

        $sequence_3 = { c20400 56 8bf1 8b4e20 33c0 3901 }
            // n = 6, score = 1700
            //   c20400               | ret                 4
            //   56                   | push                esi
            //   8bf1                 | mov                 esi, ecx
            //   8b4e20               | mov                 ecx, dword ptr [esi + 0x20]
            //   33c0                 | xor                 eax, eax
            //   3901                 | cmp                 dword ptr [ecx], eax

        $sequence_4 = { c20800 56 57 8b7c240c 8b07 8bf1 8bcf }
            // n = 7, score = 1700
            //   c20800               | ret                 8
            //   56                   | push                esi
            //   57                   | push                edi
            //   8b7c240c             | mov                 edi, dword ptr [esp + 0xc]
            //   8b07                 | mov                 eax, dword ptr [edi]
            //   8bf1                 | mov                 esi, ecx
            //   8bcf                 | mov                 ecx, edi

        $sequence_5 = { 8bc6 5e c20400 ff742408 e8???????? 59 83f8ff }
            // n = 7, score = 1700
            //   8bc6                 | mov                 eax, esi
            //   5e                   | pop                 esi
            //   c20400               | ret                 4
            //   ff742408             | push                dword ptr [esp + 8]
            //   e8????????           |                     
            //   59                   | pop                 ecx
            //   83f8ff               | cmp                 eax, -1

        $sequence_6 = { 5e c20400 b001 c3 33c0 40 }
            // n = 6, score = 1700
            //   5e                   | pop                 esi
            //   c20400               | ret                 4
            //   b001                 | mov                 al, 1
            //   c3                   | ret                 
            //   33c0                 | xor                 eax, eax
            //   40                   | inc                 eax

        $sequence_7 = { e8???????? 0fb6c0 50 ff742410 56 e8???????? }
            // n = 6, score = 1700
            //   e8????????           |                     
            //   0fb6c0               | movzx               eax, al
            //   50                   | push                eax
            //   ff742410             | push                dword ptr [esp + 0x10]
            //   56                   | push                esi
            //   e8????????           |                     

        $sequence_8 = { c3 8bff 55 8bec 83ec0c c745fc00000000 }
            // n = 6, score = 200
            //   c3                   | ret                 
            //   8bff                 | mov                 edi, edi
            //   55                   | push                ebp
            //   8bec                 | mov                 ebp, esp
            //   83ec0c               | sub                 esp, 0xc
            //   c745fc00000000       | mov                 dword ptr [ebp - 4], 0

        $sequence_9 = { dd1c24 83ec08 dd4508 dd1c24 6a0b 6a08 }
            // n = 6, score = 200
            //   dd1c24               | fstp                qword ptr [esp]
            //   83ec08               | sub                 esp, 8
            //   dd4508               | fld                 qword ptr [ebp + 8]
            //   dd1c24               | fstp                qword ptr [esp]
            //   6a0b                 | push                0xb
            //   6a08                 | push                8

        $sequence_10 = { 6a0b 6a10 e8???????? 83c41c 8be5 }
            // n = 5, score = 200
            //   6a0b                 | push                0xb
            //   6a10                 | push                0x10
            //   e8????????           |                     
            //   83c41c               | add                 esp, 0x1c
            //   8be5                 | mov                 esp, ebp

        $sequence_11 = { c743180f000000 c60700 8b4b18 894c240c 3be9 7727 83f910 }
            // n = 7, score = 100
            //   c743180f000000       | mov                 dword ptr [ebx + 0x18], 0xf
            //   c60700               | mov                 byte ptr [edi], 0
            //   8b4b18               | mov                 ecx, dword ptr [ebx + 0x18]
            //   894c240c             | mov                 dword ptr [esp + 0xc], ecx
            //   3be9                 | cmp                 ebp, ecx
            //   7727                 | ja                  0x29
            //   83f910               | cmp                 ecx, 0x10

        $sequence_12 = { 8d8c2484000000 e8???????? 8b842484000000 8b3d???????? 33d2 8944243c }
            // n = 6, score = 100
            //   8d8c2484000000       | lea                 ecx, [esp + 0x84]
            //   e8????????           |                     
            //   8b842484000000       | mov                 eax, dword ptr [esp + 0x84]
            //   8b3d????????         |                     
            //   33d2                 | xor                 edx, edx
            //   8944243c             | mov                 dword ptr [esp + 0x3c], eax

        $sequence_13 = { ffb424d0000000 6a03 6800008050 6aff 57 ff15???????? 8b35???????? }
            // n = 7, score = 100
            //   ffb424d0000000       | push                dword ptr [esp + 0xd0]
            //   6a03                 | push                3
            //   6800008050           | push                0x50800000
            //   6aff                 | push                -1
            //   57                   | push                edi
            //   ff15????????         |                     
            //   8b35????????         |                     

    condition:
        7 of them and filesize < 2793472
}

rule win_vidar_w0 {
    meta:
        description = "Yara rule for detecting Vidar stealer"
        author = "Fumik0_"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vidar"
        malpedia_version = "20190106"
        malpedia_license = "CC BY-NC-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    strings:
        $s1 = { 56 69 64 61 72 }
        $s2 = { 31 42 45 46 30 41 35 37 42 45 31 31 30 46 44 34 36 37 41 }
        
    condition:
        all of them
}

rule MALWARE_Win_Vidar {
    meta:
        author = "ditekSHen"
        description = "Detects Vidar / ArkeiStealer"
    strings:
        $s1 = "\"os_crypt\":{\"encrypted_key\":\"" fullword ascii
        $s2 = "screenshot.jpg" fullword wide
        $s3 = "Content-Disposition: form-data; name=\"" ascii
    condition:
        uint16(0) == 0x5a4d and all of them
}

rule Trojan_Vidar {
    meta:
        author = "LightDefender"
        description = "Detects Vidar"
    strings:
        $s1 = "C:\\Users\\Administrator\\Desktop\\Client\\Temp\\CBaQRjXFcr\\src\\obj\\Debug\\RoleClaimProvider.pdb" fullword ascii
        $s2 = "http://deavmi.github.io/Clippy/changelog.txt"
        $s3 = "https://deavmi.github.io/Clippy/current_version.txt"
        $s4 = "cmd.exe /c ipconfig -flushdns"
        $s5 = "chkHideClippyOnStartup"
        $s6 = "$4baf06e8-0c6b-47a4-af62-e013ec4a7555"
        $s7 = "333K333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333x333K"
        $s8 = "set_ClearClipboardToolStripMenuItem"
        $s9 = "An awesome clipboard manager"
        $s10 = "2013-07-19T03:32:47-05:00"
    condition:
        uint16(0) == 0x5a4d and (3 of them)
}
