rule spy_avemariarat {
   meta:
      description = "TrojanSpy.AveMariaRAT"
      author = "LightDefender"
      date = "2021-06-13"
      hash1 = "ac14bf805d1796f1463b5f27b79496dab9a07f5bd50336628bcfbdc2dc996acf"
   strings:
      $x1 = "cmd.exe /C ping 1.2.3.4 -n 2 -w 1000 > Nul & Del /f /q " fullword ascii
      $x2 = "c:\\windows\\system32\\user32.dll" fullword ascii
      $x3 = "C:\\Users\\Vitali Kremez\\Documents\\MidgetPorn\\workspace\\MsgBox.exe" fullword wide
      $x4 = "\\System32\\cmd.exe" fullword wide
      $s5 = "dUser32.dll" fullword wide
      $s6 = "@\\cmd.exe" fullword wide
      $s7 = "find.exe" fullword ascii
      $s8 = "SMTP Password" fullword wide
      $s9 = "Ave_Maria Stealer OpenSource github Link: https://github.com/syohex/java-simple-mine-sweeper" fullword wide
      $s10 = "\\Opera Software\\Opera Stable\\Login Data" fullword wide
      $s11 = "\\rfxvmt.dll" fullword wide
      $s12 = "\\sqlmap.dll" fullword wide
      $s13 = "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList" fullword ascii
      $s14 = "            <assemblyIdentity  name=\"Package_1_for_KB929761\" version=\"6.0.1.1\" language=\"neutral\" processorArchitecture=\"" ascii
      $s15 = "Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows Messaging Subsystem\\Profiles\\Outlook\\9375CFF0413111d3B88A00104B2A667" wide
      $s16 = "\\Comodo\\Dragon\\User Data\\Default\\Login Data" fullword wide
      $s17 = "/n:%temp%\\ellocnak.xml" fullword wide
      $s18 = "POP3 Password" fullword wide
      $s19 = "IMAP Password" fullword wide
      $s20 = "\\Google\\Chrome\\User Data\\Default\\Login Data" fullword wide
   condition:
      uint16(0) == 0x5a4d and filesize < 300KB and
      ((1 of ($x*) and 4 of them) or 5 of them)
}

rule win_ave_maria_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2020-12-22"
        version = "1"
        description = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ave_maria"
        malpedia_rule_date = "20201222"
        malpedia_hash = "30354d830a29f0fbd3714d93d94dea941d77a130"
        malpedia_version = "20201023"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 68???????? 6a67 33db 53 ff15???????? 8bf0 56 }
            // n = 7, score = 400
            //   68????????           |                     
            //   6a67                 | push                0x67
            //   33db                 | xor                 ebx, ebx
            //   53                   | push                ebx
            //   ff15????????         |                     
            //   8bf0                 | mov                 esi, eax
            //   56                   | push                esi

        $sequence_1 = { 56 8bf1 c745fc29bb66e4 57 6a04 8d45fc 8d7e08 }
            // n = 7, score = 400
            //   56                   | push                esi
            //   8bf1                 | mov                 esi, ecx
            //   c745fc29bb66e4       | mov                 dword ptr [ebp - 4], 0xe466bb29
            //   57                   | push                edi
            //   6a04                 | push                4
            //   8d45fc               | lea                 eax, [ebp - 4]
            //   8d7e08               | lea                 edi, [esi + 8]

        $sequence_2 = { ff750c ff7508 50 50 ff15???????? 33c9 8906 }
            // n = 7, score = 400
            //   ff750c               | push                dword ptr [ebp + 0xc]
            //   ff7508               | push                dword ptr [ebp + 8]
            //   50                   | push                eax
            //   50                   | push                eax
            //   ff15????????         |                     
            //   33c9                 | xor                 ecx, ecx
            //   8906                 | mov                 dword ptr [esi], eax

        $sequence_3 = { 8bc8 e8???????? eb02 8bc7 8bce 8906 e8???????? }
            // n = 7, score = 400
            //   8bc8                 | mov                 ecx, eax
            //   e8????????           |                     
            //   eb02                 | jmp                 4
            //   8bc7                 | mov                 eax, edi
            //   8bce                 | mov                 ecx, esi
            //   8906                 | mov                 dword ptr [esi], eax
            //   e8????????           |                     

        $sequence_4 = { 6a1a 5a 8d4c240c e8???????? 8b0f e8???????? 8b0f }
            // n = 7, score = 400
            //   6a1a                 | push                0x1a
            //   5a                   | pop                 edx
            //   8d4c240c             | lea                 ecx, [esp + 0xc]
            //   e8????????           |                     
            //   8b0f                 | mov                 ecx, dword ptr [edi]
            //   e8????????           |                     
            //   8b0f                 | mov                 ecx, dword ptr [edi]

        $sequence_5 = { 7409 8b01 51 ff5008 897e34 8b4e18 85c9 }
            // n = 7, score = 400
            //   7409                 | je                  0xb
            //   8b01                 | mov                 eax, dword ptr [ecx]
            //   51                   | push                ecx
            //   ff5008               | call                dword ptr [eax + 8]
            //   897e34               | mov                 dword ptr [esi + 0x34], edi
            //   8b4e18               | mov                 ecx, dword ptr [esi + 0x18]
            //   85c9                 | test                ecx, ecx

        $sequence_6 = { 8975fc e8???????? ffb5b0fdffff 56 6800100000 ff15???????? 8bf0 }
            // n = 7, score = 400
            //   8975fc               | mov                 dword ptr [ebp - 4], esi
            //   e8????????           |                     
            //   ffb5b0fdffff         | push                dword ptr [ebp - 0x250]
            //   56                   | push                esi
            //   6800100000           | push                0x1000
            //   ff15????????         |                     
            //   8bf0                 | mov                 esi, eax

        $sequence_7 = { 5d c20400 56 8bf1 57 8b4e34 85c9 }
            // n = 7, score = 400
            //   5d                   | pop                 ebp
            //   c20400               | ret                 4
            //   56                   | push                esi
            //   8bf1                 | mov                 esi, ecx
            //   57                   | push                edi
            //   8b4e34               | mov                 ecx, dword ptr [esi + 0x34]
            //   85c9                 | test                ecx, ecx

        $sequence_8 = { 33c2 894de4 33c6 c1c105 034db0 81c3a1ebd96e 03c8 }
            // n = 7, score = 400
            //   33c2                 | xor                 eax, edx
            //   894de4               | mov                 dword ptr [ebp - 0x1c], ecx
            //   33c6                 | xor                 eax, esi
            //   c1c105               | rol                 ecx, 5
            //   034db0               | add                 ecx, dword ptr [ebp - 0x50]
            //   81c3a1ebd96e         | add                 ebx, 0x6ed9eba1
            //   03c8                 | add                 ecx, eax

        $sequence_9 = { 57 8bf9 33db 57 895c2424 895c2428 895c2410 }
            // n = 7, score = 400
            //   57                   | push                edi
            //   8bf9                 | mov                 edi, ecx
            //   33db                 | xor                 ebx, ebx
            //   57                   | push                edi
            //   895c2424             | mov                 dword ptr [esp + 0x24], ebx
            //   895c2428             | mov                 dword ptr [esp + 0x28], ebx
            //   895c2410             | mov                 dword ptr [esp + 0x10], ebx

    condition:
        7 of them and filesize < 237568
}
