// From Malpedia
rule win_formbook_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-10-07"
        version = "1"
        description = "Detects win.formbook."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.formbook"
        malpedia_rule_date = "20211007"
        malpedia_hash = "e5b790e0f888f252d49063a1251ca60ec2832535"
        malpedia_version = "20211008"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 57 8b7d08 6a00 6a01 56 57 e8???????? }
            // n = 7, score = 1700
            //   57                   | push                edi
            //   8b7d08               | mov                 edi, dword ptr [ebp + 8]
            //   6a00                 | push                0
            //   6a01                 | push                1
            //   56                   | push                esi
            //   57                   | push                edi
            //   e8????????           |                     

        $sequence_1 = { 52 e8???????? 83c408 85c0 750d 8b36 394618 }
            // n = 7, score = 1700
            //   52                   | push                edx
            //   e8????????           |                     
            //   83c408               | add                 esp, 8
            //   85c0                 | test                eax, eax
            //   750d                 | jne                 0xf
            //   8b36                 | mov                 esi, dword ptr [esi]
            //   394618               | cmp                 dword ptr [esi + 0x18], eax

        $sequence_2 = { 6a02 57 8906 e8???????? 6a03 57 894604 }
            // n = 7, score = 1700
            //   6a02                 | push                2
            //   57                   | push                edi
            //   8906                 | mov                 dword ptr [esi], eax
            //   e8????????           |                     
            //   6a03                 | push                3
            //   57                   | push                edi
            //   894604               | mov                 dword ptr [esi + 4], eax

        $sequence_3 = { 50 8d8df6f7ffff 51 c745fc00000000 668985f4f7ffff e8???????? 8b7508 }
            // n = 7, score = 1700
            //   50                   | push                eax
            //   8d8df6f7ffff         | lea                 ecx, dword ptr [ebp - 0x80a]
            //   51                   | push                ecx
            //   c745fc00000000       | mov                 dword ptr [ebp - 4], 0
            //   668985f4f7ffff       | mov                 word ptr [ebp - 0x80c], ax
            //   e8????????           |                     
            //   8b7508               | mov                 esi, dword ptr [ebp + 8]

        $sequence_4 = { 56 e8???????? 83c40c 85c0 74e9 8bc6 5e }
            // n = 7, score = 1700
            //   56                   | push                esi
            //   e8????????           |                     
            //   83c40c               | add                 esp, 0xc
            //   85c0                 | test                eax, eax
            //   74e9                 | je                  0xffffffeb
            //   8bc6                 | mov                 eax, esi
            //   5e                   | pop                 esi

        $sequence_5 = { 752f 8b5604 6a0a 8d4df4 51 52 e8???????? }
            // n = 7, score = 1700
            //   752f                 | jne                 0x31
            //   8b5604               | mov                 edx, dword ptr [esi + 4]
            //   6a0a                 | push                0xa
            //   8d4df4               | lea                 ecx, dword ptr [ebp - 0xc]
            //   51                   | push                ecx
            //   52                   | push                edx
            //   e8????????           |                     

        $sequence_6 = { 6a00 50 56 e8???????? 8b0f 51 56 }
            // n = 7, score = 1700
            //   6a00                 | push                0
            //   50                   | push                eax
            //   56                   | push                esi
            //   e8????????           |                     
            //   8b0f                 | mov                 ecx, dword ptr [edi]
            //   51                   | push                ecx
            //   56                   | push                esi

        $sequence_7 = { 004e2a 53 56 e8???????? 83c408 5f 5e }
            // n = 7, score = 1700
            //   004e2a               | add                 byte ptr [esi + 0x2a], cl
            //   53                   | push                ebx
            //   56                   | push                esi
            //   e8????????           |                     
            //   83c408               | add                 esp, 8
            //   5f                   | pop                 edi
            //   5e                   | pop                 esi

    condition:
        7 of them and filesize < 371712
}

rule Formbook
{
    meta:
        author = "kevoreilly"
        description = "Formbook Anti-analysis Bypass"
        cape_options = "bp0=$remap_ntdll-25,action0=setedx:ntdll,count=0"
    strings:
        $remap_ntdll = {6A 00 6A 04 8D 4D ?? 51 6A 07 52 56 E8 [4] 8B 45 ?? 83 C4 20 3B 06 0F 95 C1 84 C9 74 0E 33 C0 B2 FF 00 54 30 ?? 40 83 F8 0D 72 F6}
    condition:
        ($remap_ntdll)
}

rule spy_formbook_june_15 {
   meta:
      description = "TrojanSpy.Formbook"
      author = "LightDefender"
      date = "2021-06-15"
   strings:
      $s1 = "ftpPassword" fullword ascii
      $s2 = "ftpUsername" fullword ascii
      $s3 = "ftpServer" fullword ascii
      $s4 = "ssPassword" fullword ascii
      $s5 = "btnFTPUpload" fullword ascii
      $s6 = "flickrauthtoken" fullword ascii
      $s7 = "flickruser" fullword ascii
      $s8 = "clipboardData4" fullword ascii
      $s9 = "clipboardData3" fullword ascii
      $s10 = "clipboardData2" fullword ascii
      $s11 = "clipboardData1" fullword ascii
      $s12 = "clipboardData0" fullword ascii
      $s13 = "ClipboardManager.Properties" fullword ascii
      $s14 = "ssUpload" fullword ascii
      $s15 = "Uploading" fullword wide
      $s16 = "noscrnshots" fullword wide
      $s17 = "Clipboard Memorizer is already running." fullword wide
      $s18 = "Screen Info" fullword wide
      $s19 = "Adam Lamers" fullword wide
      $s20 = "<Password></Password>" fullword wide
      $s21 = "Created By Adam Lamers 2009" fullword wide
      $s22 = {00 00 28 34 00 00 0A 0A 12 01 FE 15 1F 00 00 01}
      $s23 = {00 02 7B 79 00 00 04 04 6F F3 00 00 0A 6F F4 00}
      $s24 = {00 02 7B 29 00 00 04 02 7B 2D 00 00 04 6F 84 00}
      $s25 = "There was an error connecting to the spread server - cannot update the gauge. Check your connection to the network and retry"
      $s26 = "Could not find a spreadometer.  Check it is connected properly and click retry to scan again."
      $s27 = "valuation_model_definition_template"
      $s28 = "https://github.com/Laicure/HostsY"
      $s29 = "f3platform/api/v1/selector/"
      $s30 = "DFEA2964B5DEEDEA7B1EF077DE529C3959E6788BDBB3441E70C77A1AE875BB48"
      
      $x0 = "#GUID" ascii
      $x1 = "#Strings" ascii
      $x2 = "#Blob" ascii
      $x3 = "Microsoft.VisualBasic" ascii
      $x4 = "16.0.0.0" fullword ascii
   condition:
      ( uint16(0) == 0x5a4d and filesize < 2000KB and 7 of them) or ( all of them )
 }
