rule win_qakbot_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2020-12-22"
        version = "1"
        description = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.qakbot"
        malpedia_rule_date = "20201222"
        malpedia_hash = "30354d830a29f0fbd3714d93d94dea941d77a130"
        malpedia_version = "20201023"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 57 ff15???????? 33c0 85f6 0f94c0 }
            // n = 5, score = 4000
            //   57                   | push                edi
            //   ff15????????         |                     
            //   33c0                 | xor                 eax, eax
            //   85f6                 | test                esi, esi
            //   0f94c0               | sete                al

        $sequence_1 = { 50 ff5508 8bf0 59 }
            // n = 4, score = 4000
            //   50                   | push                eax
            //   ff5508               | call                dword ptr [ebp + 8]
            //   8bf0                 | mov                 esi, eax
            //   59                   | pop                 ecx

        $sequence_2 = { 8b4df8 8908 ff75fc ff15???????? }
            // n = 4, score = 3800
            //   8b4df8               | mov                 ecx, dword ptr [ebp - 8]
            //   8908                 | mov                 dword ptr [eax], ecx
            //   ff75fc               | push                dword ptr [ebp - 4]
            //   ff15????????         |                     

        $sequence_3 = { c1e80b 33d0 8bc2 25ad583aff c1e007 33d0 }
            // n = 6, score = 3800
            //   c1e80b               | shr                 eax, 0xb
            //   33d0                 | xor                 edx, eax
            //   8bc2                 | mov                 eax, edx
            //   25ad583aff           | and                 eax, 0xff3a58ad
            //   c1e007               | shl                 eax, 7
            //   33d0                 | xor                 edx, eax

        $sequence_4 = { 8b1481 40 8981c0090000 8bc2 c1e80b 33d0 8bc2 }
            // n = 7, score = 3800
            //   8b1481               | mov                 edx, dword ptr [ecx + eax*4]
            //   40                   | inc                 eax
            //   8981c0090000         | mov                 dword ptr [ecx + 0x9c0], eax
            //   8bc2                 | mov                 eax, edx
            //   c1e80b               | shr                 eax, 0xb
            //   33d0                 | xor                 edx, eax
            //   8bc2                 | mov                 eax, edx

        $sequence_5 = { c3 33c9 3d80000000 0f94c1 }
            // n = 4, score = 3800
            //   c3                   | ret                 
            //   33c9                 | xor                 ecx, ecx
            //   3d80000000           | cmp                 eax, 0x80
            //   0f94c1               | sete                cl

        $sequence_6 = { 57 6a00 6a02 ff15???????? 8bf8 83c8ff }
            // n = 6, score = 3800
            //   57                   | push                edi
            //   6a00                 | push                0
            //   6a02                 | push                2
            //   ff15????????         |                     
            //   8bf8                 | mov                 edi, eax
            //   83c8ff               | or                  eax, 0xffffffff

        $sequence_7 = { 750c 57 ff15???????? 6afe 58 }
            // n = 5, score = 3800
            //   750c                 | jne                 0xe
            //   57                   | push                edi
            //   ff15????????         |                     
            //   6afe                 | push                -2
            //   58                   | pop                 eax

        $sequence_8 = { 8d45f8 56 50 e8???????? 8d45f4 }
            // n = 5, score = 3800
            //   8d45f8               | lea                 eax, [ebp - 8]
            //   56                   | push                esi
            //   50                   | push                eax
            //   e8????????           |                     
            //   8d45f4               | lea                 eax, [ebp - 0xc]

        $sequence_9 = { 7507 c74508???????? e8???????? 85c0 7d08 }
            // n = 5, score = 3800
            //   7507                 | jne                 9
            //   c74508????????       |                     
            //   e8????????           |                     
            //   85c0                 | test                eax, eax
            //   7d08                 | jge                 0xa

        $sequence_10 = { 50 e8???????? 8b06 47 59 }
            // n = 5, score = 3800
            //   50                   | push                eax
            //   e8????????           |                     
            //   8b06                 | mov                 eax, dword ptr [esi]
            //   47                   | inc                 edi
            //   59                   | pop                 ecx

        $sequence_11 = { 740d 8d45fc 6a00 50 e8???????? 59 }
            // n = 6, score = 3800
            //   740d                 | je                  0xf
            //   8d45fc               | lea                 eax, [ebp - 4]
            //   6a00                 | push                0
            //   50                   | push                eax
            //   e8????????           |                     
            //   59                   | pop                 ecx

        $sequence_12 = { 33c0 7402 ebfa e8???????? }
            // n = 4, score = 3700
            //   33c0                 | xor                 eax, eax
            //   7402                 | je                  4
            //   ebfa                 | jmp                 0xfffffffc
            //   e8????????           |                     

        $sequence_13 = { ebfa 83c8ff eb02 33c0 }
            // n = 4, score = 3500
            //   ebfa                 | jmp                 0xfffffffc
            //   83c8ff               | or                  eax, 0xffffffff
            //   eb02                 | jmp                 4
            //   33c0                 | xor                 eax, eax

        $sequence_14 = { 85c0 750d 33d2 7402 }
            // n = 4, score = 3500
            //   85c0                 | test                eax, eax
            //   750d                 | jne                 0xf
            //   33d2                 | xor                 edx, edx
            //   7402                 | je                  4

        $sequence_15 = { 6a00 ff15???????? a3???????? 833d????????00 750b 33c0 7402 }
            // n = 7, score = 3500
            //   6a00                 | push                0
            //   ff15????????         |                     
            //   a3????????           |                     
            //   833d????????00       |                     
            //   750b                 | jne                 0xd
            //   33c0                 | xor                 eax, eax
            //   7402                 | je                  4

        $sequence_16 = { ff750c 8d85d8feffff 50 ff5508 }
            // n = 4, score = 3500
            //   ff750c               | push                dword ptr [ebp + 0xc]
            //   8d85d8feffff         | lea                 eax, [ebp - 0x128]
            //   50                   | push                eax
            //   ff5508               | call                dword ptr [ebp + 8]

        $sequence_17 = { 7404 33c0 eb27 6a00 6a00 }
            // n = 5, score = 3500
            //   7404                 | je                  6
            //   33c0                 | xor                 eax, eax
            //   eb27                 | jmp                 0x29
            //   6a00                 | push                0
            //   6a00                 | push                0

        $sequence_18 = { ebfa eb06 33c0 7402 }
            // n = 4, score = 3500
            //   ebfa                 | jmp                 0xfffffffc
            //   eb06                 | jmp                 8
            //   33c0                 | xor                 eax, eax
            //   7402                 | je                  4

        $sequence_19 = { 7412 8d85d8feffff 50 57 ff15???????? 85c0 75d9 }
            // n = 7, score = 3500
            //   7412                 | je                  0x14
            //   8d85d8feffff         | lea                 eax, [ebp - 0x128]
            //   50                   | push                eax
            //   57                   | push                edi
            //   ff15????????         |                     
            //   85c0                 | test                eax, eax
            //   75d9                 | jne                 0xffffffdb

        $sequence_20 = { 83c40c 33c0 5b 5f 5e c9 c3 }
            // n = 7, score = 3500
            //   83c40c               | add                 esp, 0xc
            //   33c0                 | xor                 eax, eax
            //   5b                   | pop                 ebx
            //   5f                   | pop                 edi
            //   5e                   | pop                 esi
            //   c9                   | leave               
            //   c3                   | ret                 

        $sequence_21 = { 7402 ebfa 83c8ff e9???????? }
            // n = 4, score = 3500
            //   7402                 | je                  4
            //   ebfa                 | jmp                 0xfffffffc
            //   83c8ff               | or                  eax, 0xffffffff
            //   e9????????           |                     

        $sequence_22 = { 8b84248c000000 8b4050 89442470 8b84248c000000 8b4034 8944246c 89e0 }
            // n = 7, score = 100
            //   8b84248c000000       | mov                 eax, dword ptr [esp + 0x8c]
            //   8b4050               | mov                 eax, dword ptr [eax + 0x50]
            //   89442470             | mov                 dword ptr [esp + 0x70], eax
            //   8b84248c000000       | mov                 eax, dword ptr [esp + 0x8c]
            //   8b4034               | mov                 eax, dword ptr [eax + 0x34]
            //   8944246c             | mov                 dword ptr [esp + 0x6c], eax
            //   89e0                 | mov                 eax, esp

        $sequence_23 = { 5f 5b 5d c3 31c0 8944242c 89442428 }
            // n = 7, score = 100
            //   5f                   | pop                 edi
            //   5b                   | pop                 ebx
            //   5d                   | pop                 ebp
            //   c3                   | ret                 
            //   31c0                 | xor                 eax, eax
            //   8944242c             | mov                 dword ptr [esp + 0x2c], eax
            //   89442428             | mov                 dword ptr [esp + 0x28], eax

        $sequence_24 = { 8b5824 89442438 8b842480000000 01f8 81c283f803c4 }
            // n = 5, score = 100
            //   8b5824               | mov                 ebx, dword ptr [eax + 0x24]
            //   89442438             | mov                 dword ptr [esp + 0x38], eax
            //   8b842480000000       | mov                 eax, dword ptr [esp + 0x80]
            //   01f8                 | add                 eax, edi
            //   81c283f803c4         | add                 edx, 0xc403f883

        $sequence_25 = { 81e2ffff0000 8b75ec 81c622be8b8f 01f2 8b75dc 01d6 8975d0 }
            // n = 7, score = 100
            //   81e2ffff0000         | and                 edx, 0xffff
            //   8b75ec               | mov                 esi, dword ptr [ebp - 0x14]
            //   81c622be8b8f         | add                 esi, 0x8f8bbe22
            //   01f2                 | add                 edx, esi
            //   8b75dc               | mov                 esi, dword ptr [ebp - 0x24]
            //   01d6                 | add                 esi, edx
            //   8975d0               | mov                 dword ptr [ebp - 0x30], esi

        $sequence_26 = { 8b5508 83f800 89442414 894c2410 8954240c }
            // n = 5, score = 100
            //   8b5508               | mov                 edx, dword ptr [ebp + 8]
            //   83f800               | cmp                 eax, 0
            //   89442414             | mov                 dword ptr [esp + 0x14], eax
            //   894c2410             | mov                 dword ptr [esp + 0x10], ecx
            //   8954240c             | mov                 dword ptr [esp + 0xc], edx

        $sequence_27 = { c645ebda 662b4df2 668988f4000000 c78008010000611a0000 66c780f80000000b01 83c410 }
            // n = 6, score = 100
            //   c645ebda             | mov                 byte ptr [ebp - 0x15], 0xda
            //   662b4df2             | sub                 cx, word ptr [ebp - 0xe]
            //   668988f4000000       | mov                 word ptr [eax + 0xf4], cx
            //   c78008010000611a0000     | mov    dword ptr [eax + 0x108], 0x1a61
            //   66c780f80000000b01     | mov    word ptr [eax + 0xf8], 0x10b
            //   83c410               | add                 esp, 0x10

        $sequence_28 = { 8b4d0c 8b5508 31f6 8b5244 83fa00 8945f4 894df0 }
            // n = 7, score = 100
            //   8b4d0c               | mov                 ecx, dword ptr [ebp + 0xc]
            //   8b5508               | mov                 edx, dword ptr [ebp + 8]
            //   31f6                 | xor                 esi, esi
            //   8b5244               | mov                 edx, dword ptr [edx + 0x44]
            //   83fa00               | cmp                 edx, 0
            //   8945f4               | mov                 dword ptr [ebp - 0xc], eax
            //   894df0               | mov                 dword ptr [ebp - 0x10], ecx

        $sequence_29 = { 8b4c2418 39cf 89442410 897c2408 74c8 8b442408 8b4c2438 }
            // n = 7, score = 100
            //   8b4c2418             | mov                 ecx, dword ptr [esp + 0x18]
            //   39cf                 | cmp                 edi, ecx
            //   89442410             | mov                 dword ptr [esp + 0x10], eax
            //   897c2408             | mov                 dword ptr [esp + 8], edi
            //   74c8                 | je                  0xffffffca
            //   8b442408             | mov                 eax, dword ptr [esp + 8]
            //   8b4c2438             | mov                 ecx, dword ptr [esp + 0x38]

    condition:
        7 of them and filesize < 958464
}
