rule win_trickbot_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2020-12-22"
        version = "1"
        description = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.trickbot"
        malpedia_rule_date = "20201222"
        malpedia_hash = "30354d830a29f0fbd3714d93d94dea941d77a130"
        malpedia_version = "20201023"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 2500000080 f7d8 1bc0 83e002 83c002 eb0d }
            // n = 6, score = 4500
            //   2500000080           | mov                 edx, dword ptr [ecx + 0x18]
            //   f7d8                 | dec                 eax
            //   1bc0                 | mov                 dword ptr [esp + 0x40], eax
            //   83e002               | dec                 eax
            //   83c002               | mov                 eax, dword ptr [ecx + 0x48]
            //   eb0d                 | dec                 eax

        $sequence_1 = { 83e002 83c002 eb0d 2500000080 f7d8 1bc0 }
            // n = 6, score = 4500
            //   83e002               | dec                 eax
            //   83c002               | mov                 eax, dword ptr [ecx + 0x48]
            //   eb0d                 | dec                 eax
            //   2500000080           | mov                 dword ptr [esp + 0x38], eax
            //   f7d8                 | dec                 eax
            //   1bc0                 | mov                 eax, dword ptr [ecx + 0x40]

        $sequence_2 = { 7429 a900000040 7411 2500000080 }
            // n = 4, score = 4500
            //   7429                 | mov                 eax, dword ptr [ecx + 0x20]
            //   a900000040           | dec                 eax
            //   7411                 | mov                 edx, dword ptr [ecx + 0x18]
            //   2500000080           | dec                 eax

        $sequence_3 = { f7d8 1bc0 83e070 83c010 eb25 }
            // n = 5, score = 4500
            //   f7d8                 | dec                 eax
            //   1bc0                 | mov                 edx, dword ptr [ecx + 0x18]
            //   83e070               | dec                 eax
            //   83c010               | mov                 dword ptr [esp + 0x40], eax
            //   eb25                 | dec                 eax

        $sequence_4 = { 1bc0 83e020 83c020 eb36 2500000080 f7d8 }
            // n = 6, score = 4500
            //   1bc0                 | mov                 dword ptr [esp + 0x38], eax
            //   83e020               | dec                 eax
            //   83c020               | mov                 eax, dword ptr [ecx + 0x48]
            //   eb36                 | dec                 esp
            //   2500000080           | mov                 edx, dword ptr [ecx]
            //   f7d8                 | dec                 esp

        $sequence_5 = { 8b07 a900000020 7429 a900000040 }
            // n = 4, score = 4300
            //   8b07                 | sbb                 eax, eax
            //   a900000020           | and                 eax, 0x20
            //   7429                 | add                 eax, 0x20
            //   a900000040           | jmp                 0x3e

        $sequence_6 = { 895df8 895df4 895dec 66c745f00005 }
            // n = 4, score = 3500
            //   895df8               | test                eax, 0x40000000
            //   895df4               | je                  0x1d
            //   895dec               | test                eax, 0x20000000
            //   66c745f00005         | je                  0x30

        $sequence_7 = { c705????????fdffffff c705????????feffffff c705????????ffffffff e8???????? }
            // n = 4, score = 3400
            //   c705????????fdffffff     |     
            //   c705????????feffffff     |     
            //   c705????????ffffffff     |     
            //   e8????????           |                     

        $sequence_8 = { e8???????? 33c9 3dc4431cfc 0f94c1 83e101 }
            // n = 5, score = 3400
            //   e8????????           |                     
            //   33c9                 | mov                 dword ptr [ebp - 0x14], ebx
            //   3dc4431cfc           | mov                 word ptr [ebp - 0x10], 0x500
            //   0f94c1               | mov                 dword ptr [ebp - 8], ebx
            //   83e101               | mov                 dword ptr [ebp - 0xc], ebx

        $sequence_9 = { 33ff 57 6880000000 6a02 57 6a01 68000000c0 }
            // n = 7, score = 3400
            //   33ff                 | add                 eax, 0x20
            //   57                   | jmp                 0x3b
            //   6880000000           | and                 eax, 0x80000000
            //   6a02                 | neg                 eax
            //   57                   | sbb                 eax, eax
            //   6a01                 | and                 eax, 0x70
            //   68000000c0           | jmp                 0xf

        $sequence_10 = { 2500000080 f7d8 1bc0 83e007 40 8b4fe8 }
            // n = 6, score = 3000
            //   2500000080           | mov                 edx, dword ptr [ecx]
            //   f7d8                 | dec                 esp
            //   1bc0                 | mov                 ecx, dword ptr [ecx + 0x28]
            //   83e007               | dec                 esp
            //   40                   | mov                 eax, dword ptr [ecx + 0x20]
            //   8b4fe8               | dec                 eax

        $sequence_11 = { 8b45fc 8d1489 8d0cd0 8b4114 }
            // n = 4, score = 3000
            //   8b45fc               | mov                 dword ptr [esp + 0x30], eax
            //   8d1489               | dec                 eax
            //   8d0cd0               | mov                 eax, dword ptr [ecx + 0x38]
            //   8b4114               | dec                 eax

        $sequence_12 = { 50 ff15???????? 8b4604 85c0 7407 50 ff15???????? }
            // n = 7, score = 3000
            //   50                   | dec                 eax
            //   ff15????????         |                     
            //   8b4604               | mov                 eax, dword ptr [ecx + 0x38]
            //   85c0                 | dec                 eax
            //   7407                 | mov                 dword ptr [esp + 0x28], eax
            //   50                   | dec                 eax
            //   ff15????????         |                     

        $sequence_13 = { 488b5118 4889442440 488b4148 4889442438 }
            // n = 4, score = 2800
            //   488b5118             | dec                 eax
            //   4889442440           | mov                 ecx, dword ptr [ecx + 0x10]
            //   488b4148             | call                eax
            //   4889442438           | dec                 esp

        $sequence_14 = { 488b01 488b5118 488b4910 ffd0 }
            // n = 4, score = 2800
            //   488b01               | dec                 eax
            //   488b5118             | mov                 dword ptr [esp + 0x38], eax
            //   488b4910             | dec                 eax
            //   ffd0                 | mov                 eax, dword ptr [ecx + 0x40]

        $sequence_15 = { 33db 53 53 6a03 53 6a01 6800010000 }
            // n = 7, score = 2800
            //   33db                 | mov                 eax, dword ptr [ecx + 0x30]
            //   53                   | dec                 esp
            //   53                   | mov                 edx, dword ptr [ecx]
            //   6a03                 | dec                 esp
            //   53                   | mov                 ecx, dword ptr [ecx + 0x28]
            //   6a01                 | dec                 esp
            //   6800010000           | mov                 eax, dword ptr [ecx + 0x20]

        $sequence_16 = { 488b4148 4889442438 488b4140 4889442430 488b4138 4889442428 488b4130 }
            // n = 7, score = 2800
            //   488b4148             | dec                 eax
            //   4889442438           | mov                 dword ptr [esp + 0x38], eax
            //   488b4140             | dec                 esp
            //   4889442430           | mov                 eax, dword ptr [ecx + 0x20]
            //   488b4138             | dec                 eax
            //   4889442428           | mov                 edx, dword ptr [ecx + 0x18]
            //   488b4130             | dec                 eax

        $sequence_17 = { 488b4148 4c8b11 4c8b4928 4c8b4120 488b5118 }
            // n = 5, score = 2800
            //   488b4148             | mov                 dword ptr [esp + 0x38], eax
            //   4c8b11               | dec                 eax
            //   4c8b4928             | mov                 eax, dword ptr [ecx + 0x40]
            //   4c8b4120             | dec                 eax
            //   488b5118             | mov                 dword ptr [esp + 0x30], eax

        $sequence_18 = { 488b01 4c8b4120 488b5118 488b4910 }
            // n = 4, score = 2800
            //   488b01               | mov                 eax, dword ptr [ecx + 0x40]
            //   4c8b4120             | dec                 eax
            //   488b5118             | mov                 dword ptr [esp + 0x30], eax
            //   488b4910             | dec                 eax

        $sequence_19 = { 4c8b4120 488b5118 4889442438 488b4140 }
            // n = 4, score = 2800
            //   4c8b4120             | dec                 esp
            //   488b5118             | mov                 eax, dword ptr [ecx + 0x20]
            //   4889442438           | dec                 eax
            //   488b4140             | mov                 edx, dword ptr [ecx + 0x18]

        $sequence_20 = { 488b4138 4889442428 488b4130 488b4910 4889442420 41ffd2 }
            // n = 6, score = 2800
            //   488b4138             | dec                 eax
            //   4889442428           | mov                 edx, dword ptr [ecx + 0x18]
            //   488b4130             | dec                 eax
            //   488b4910             | mov                 dword ptr [esp + 0x40], eax
            //   4889442420           | dec                 eax
            //   41ffd2               | mov                 eax, dword ptr [ecx + 0x48]

        $sequence_21 = { 48397c2430 0f94c3 8bc3 488b5c2450 }
            // n = 4, score = 2500
            //   48397c2430           | dec                 eax
            //   0f94c3               | mov                 dword ptr [esp + 0x38], eax
            //   8bc3                 | dec                 eax
            //   488b5c2450           | mov                 eax, dword ptr [ecx + 0x40]

        $sequence_22 = { 740b b801000000 4585db 0f49d8 }
            // n = 4, score = 2100
            //   740b                 | jmp                 0x27
            //   b801000000           | test                eax, 0x40000000
            //   4585db               | je                  0x13
            //   0f49d8               | and                 eax, 0x80000000

        $sequence_23 = { e8???????? e8???????? e8???????? 33c9 ff15???????? }
            // n = 5, score = 1600
            //   e8????????           |                     
            //   e8????????           |                     
            //   e8????????           |                     
            //   33c9                 | mov                 dword ptr [esp + 0x28], eax
            //   ff15????????         |                     

        $sequence_24 = { 83780400 7404 8b4008 c3 }
            // n = 4, score = 1600
            //   83780400             | dec                 esp
            //   7404                 | mov                 edx, dword ptr [ecx]
            //   8b4008               | dec                 esp
            //   c3                   | mov                 ecx, dword ptr [ecx + 0x28]

        $sequence_25 = { 85c0 751b 68e8030000 ff15???????? }
            // n = 4, score = 1600
            //   85c0                 | and                 eax, 0x80000000
            //   751b                 | neg                 eax
            //   68e8030000           | sbb                 eax, eax
            //   ff15????????         |                     

        $sequence_26 = { d1e8 03c2 c1e806 6bc05f }
            // n = 4, score = 1600
            //   d1e8                 | mov                 dword ptr [esp + 0x28], eax
            //   03c2                 | dec                 eax
            //   c1e806               | mov                 eax, dword ptr [ecx + 0x30]
            //   6bc05f               | dec                 eax

        $sequence_27 = { c3 6a01 ff15???????? 50 }
            // n = 4, score = 1500
            //   c3                   | dec                 eax
            //   6a01                 | mov                 eax, dword ptr [ecx + 0x40]
            //   ff15????????         |                     
            //   50                   | dec                 eax

        $sequence_28 = { e8???????? 53 e8???????? 83c404 33db }
            // n = 5, score = 1400
            //   e8????????           |                     
            //   53                   | dec                 esp
            //   e8????????           |                     
            //   83c404               | mov                 eax, dword ptr [ecx + 0x20]
            //   33db                 | dec                 eax

        $sequence_29 = { 5f 8930 8b45fc 5e }
            // n = 4, score = 1400
            //   5f                   | mov                 dword ptr [esp + 0x30], eax
            //   8930                 | dec                 eax
            //   8b45fc               | mov                 eax, dword ptr [ecx + 0x38]
            //   5e                   | dec                 eax

        $sequence_30 = { 6a40 6800300000 6a70 6a00 }
            // n = 4, score = 1400
            //   6a40                 | dec                 eax
            //   6800300000           | mov                 dword ptr [esp + 0x28], eax
            //   6a70                 | dec                 eax
            //   6a00                 | mov                 eax, dword ptr [ecx + 0x30]

        $sequence_31 = { 51 68e9fd0000 50 e8???????? }
            // n = 4, score = 1400
            //   51                   | mov                 dword ptr [esp + 0x30], eax
            //   68e9fd0000           | dec                 eax
            //   50                   | mov                 eax, dword ptr [ecx + 0x38]
            //   e8????????           |                     

        $sequence_32 = { 8bc1 66ad 85c0 741c }
            // n = 4, score = 1300
            //   8bc1                 | mov                 eax, ecx
            //   66ad                 | lodsw               ax, word ptr [esi]
            //   85c0                 | test                eax, eax
            //   741c                 | je                  0x1e

        $sequence_33 = { 59 03d0 52 ebdc 89450c }
            // n = 5, score = 1300
            //   59                   | pop                 ecx
            //   03d0                 | add                 edx, eax
            //   52                   | push                edx
            //   ebdc                 | jmp                 0xffffffde
            //   89450c               | mov                 dword ptr [ebp + 0xc], eax

        $sequence_34 = { 8b05???????? 85c0 7f0b e8???????? }
            // n = 4, score = 1300
            //   8b05????????         |                     
            //   85c0                 | dec                 eax
            //   7f0b                 | mov                 eax, dword ptr [ecx + 0x30]
            //   e8????????           |                     

        $sequence_35 = { e8???????? 83f801 7411 ba0a000000 }
            // n = 4, score = 1300
            //   e8????????           |                     
            //   83f801               | dec                 esp
            //   7411                 | mov                 eax, dword ptr [ecx + 0x20]
            //   ba0a000000           | dec                 eax

        $sequence_36 = { 50 8b450c ff4d0c ba28000000 f7e2 }
            // n = 5, score = 1200
            //   50                   | push                eax
            //   8b450c               | mov                 eax, dword ptr [ebp + 0xc]
            //   ff4d0c               | dec                 dword ptr [ebp + 0xc]
            //   ba28000000           | mov                 edx, 0x28
            //   f7e2                 | mul                 edx

        $sequence_37 = { c1e102 2bc1 8b00 894508 }
            // n = 4, score = 1200
            //   c1e102               | shl                 ecx, 2
            //   2bc1                 | sub                 eax, ecx
            //   8b00                 | mov                 eax, dword ptr [eax]
            //   894508               | mov                 dword ptr [ebp + 8], eax

        $sequence_38 = { 85c0 741c 3bc1 7213 }
            // n = 4, score = 1200
            //   85c0                 | test                eax, eax
            //   741c                 | je                  0x1e
            //   3bc1                 | cmp                 eax, ecx
            //   7213                 | jb                  0x15

        $sequence_39 = { 7405 e8???????? ff15???????? 8bc3 }
            // n = 4, score = 1200
            //   7405                 | mov                 dword ptr [esp + 0x40], eax
            //   e8????????           |                     
            //   ff15????????         |                     
            //   8bc3                 | dec                 esp

        $sequence_40 = { 2bc1 8b00 3bc7 72f2 }
            // n = 4, score = 1100
            //   2bc1                 | sub                 eax, ecx
            //   8b00                 | mov                 eax, dword ptr [eax]
            //   3bc7                 | cmp                 eax, edi
            //   72f2                 | jb                  0xfffffff4

        $sequence_41 = { 8b5510 8b4a04 ff5508 50 51 50 }
            // n = 6, score = 1100
            //   8b5510               | mov                 edx, dword ptr [ebp + 0x10]
            //   8b4a04               | mov                 ecx, dword ptr [edx + 4]
            //   ff5508               | call                dword ptr [ebp + 8]
            //   50                   | push                eax
            //   51                   | push                ecx
            //   50                   | push                eax

        $sequence_42 = { 03d0 895510 8b4a04 ff5508 8b5510 }
            // n = 5, score = 1100
            //   03d0                 | add                 edx, eax
            //   895510               | mov                 dword ptr [ebp + 0x10], edx
            //   8b4a04               | mov                 ecx, dword ptr [edx + 4]
            //   ff5508               | call                dword ptr [ebp + 8]
            //   8b5510               | mov                 edx, dword ptr [ebp + 0x10]

        $sequence_43 = { 8b47f8 8b0f 8945f4 3bc1 7703 894df4 8b47fc }
            // n = 7, score = 1000
            //   8b47f8               | mov                 eax, dword ptr [ecx + 0x48]
            //   8b0f                 | dec                 eax
            //   8945f4               | mov                 dword ptr [esp + 0x38], eax
            //   3bc1                 | dec                 eax
            //   7703                 | mov                 eax, dword ptr [ecx + 0x40]
            //   894df4               | dec                 eax
            //   8b47fc               | mov                 eax, dword ptr [ecx + 0x48]

        $sequence_44 = { ba28000000 f7e2 8d9500040000 03d0 }
            // n = 4, score = 1000
            //   ba28000000           | sbb                 eax, eax
            //   f7e2                 | and                 eax, 0x70
            //   8d9500040000         | add                 eax, 0x10
            //   03d0                 | jmp                 0x36

        $sequence_45 = { 89742428 c744242000001f00 ff15???????? 85c0 7911 }
            // n = 5, score = 900
            //   89742428             | mov                 dword ptr [esp + 0x28], eax
            //   c744242000001f00     | dec                 eax
            //   ff15????????         |                     
            //   85c0                 | mov                 eax, dword ptr [ecx + 0x30]
            //   7911                 | dec                 eax

        $sequence_46 = { 666666660f1f840000000000 8b4728 8bd6 83f801 }
            // n = 4, score = 900
            //   666666660f1f840000000000     | dec    eax
            //   8b4728               | mov                 dword ptr [esp + 0x30], eax
            //   8bd6                 | dec                 eax
            //   83f801               | mov                 eax, dword ptr [ecx + 0x38]

        $sequence_47 = { c744242000300000 ff15???????? 85c0 7916 }
            // n = 4, score = 900
            //   c744242000300000     | mov                 dword ptr [esp + 0x38], eax
            //   ff15????????         |                     
            //   85c0                 | dec                 eax
            //   7916                 | mov                 eax, dword ptr [ecx + 0x40]

        $sequence_48 = { e9???????? 803a23 7545 0fb64201 }
            // n = 4, score = 900
            //   e9????????           |                     
            //   803a23               | dec                 eax
            //   7545                 | mov                 edx, dword ptr [ecx + 0x18]
            //   0fb64201             | dec                 eax

        $sequence_49 = { e8???????? 85c0 7507 e8???????? eb5b }
            // n = 5, score = 900
            //   e8????????           |                     
            //   85c0                 | dec                 eax
            //   7507                 | mov                 dword ptr [esp + 0x28], eax
            //   e8????????           |                     
            //   eb5b                 | dec                 eax

        $sequence_50 = { 33d2 ff15???????? 85c0 7909 8bc8 }
            // n = 5, score = 900
            //   33d2                 | mov                 dword ptr [esp + 0x38], eax
            //   ff15????????         |                     
            //   85c0                 | dec                 eax
            //   7909                 | mov                 eax, dword ptr [ecx + 0x40]
            //   8bc8                 | dec                 eax

        $sequence_51 = { e8???????? 8bd8 85c0 740f 8bc8 }
            // n = 5, score = 900
            //   e8????????           |                     
            //   8bd8                 | mov                 dword ptr [esp + 0x30], eax
            //   85c0                 | dec                 eax
            //   740f                 | mov                 eax, dword ptr [ecx + 0x38]
            //   8bc8                 | dec                 eax

        $sequence_52 = { 85c0 7911 8bc8 e8???????? bb11000000 e9???????? }
            // n = 6, score = 900
            //   85c0                 | mov                 dword ptr [esp + 0x38], eax
            //   7911                 | dec                 eax
            //   8bc8                 | mov                 eax, dword ptr [ecx + 0x40]
            //   e8????????           |                     
            //   bb11000000           | dec                 eax
            //   e9????????           |                     

        $sequence_53 = { 41 41 41 41 50 2bc1 8b00 }
            // n = 7, score = 800
            //   41                   | sbb                 eax, eax
            //   41                   | and                 eax, 0x80000000
            //   41                   | neg                 eax
            //   41                   | sbb                 eax, eax
            //   50                   | and                 eax, 7
            //   2bc1                 | sbb                 eax, eax
            //   8b00                 | and                 eax, 0x70

        $sequence_54 = { 3bc1 7213 2bc1 51 }
            // n = 4, score = 700
            //   3bc1                 | test                eax, 0x40000000
            //   7213                 | je                  0x18
            //   2bc1                 | and                 eax, 0x80000000
            //   51                   | neg                 eax

        $sequence_55 = { 59 50 e2fd 8bc7 57 }
            // n = 5, score = 700
            //   59                   | neg                 eax
            //   50                   | jmp                 0x27
            //   e2fd                 | test                eax, 0x40000000
            //   8bc7                 | je                  0x18
            //   57                   | and                 eax, 0x80000000

        $sequence_56 = { 03c8 8b01 59 03d0 }
            // n = 4, score = 700
            //   03c8                 | jmp                 0x2d
            //   8b01                 | test                eax, 0x40000000
            //   59                   | je                  0x20
            //   03d0                 | neg                 eax

        $sequence_57 = { 68f0ff0000 59 8bf7 8bd7 fc }
            // n = 5, score = 700
            //   68f0ff0000           | sbb                 eax, eax
            //   59                   | and                 eax, 2
            //   8bf7                 | add                 eax, 2
            //   8bd7                 | jmp                 0x17
            //   fc                   | and                 eax, 2

        $sequence_58 = { 8bc7 e8???????? 85c0 0f849f000000 }
            // n = 4, score = 700
            //   8bc7                 | mov                 ecx, dword ptr [ecx + 0x28]
            //   e8????????           |                     
            //   85c0                 | dec                 esp
            //   0f849f000000         | mov                 eax, dword ptr [ecx + 0x20]

        $sequence_59 = { 2bc1 c1e002 51 8bcf 03c8 }
            // n = 5, score = 600
            //   2bc1                 | neg                 eax
            //   c1e002               | sbb                 eax, eax
            //   51                   | and                 eax, 0x70
            //   8bcf                 | add                 eax, 0x10
            //   03c8                 | jmp                 0x2f

        $sequence_60 = { e8???????? 8bc8 33d2 8bc7 f7f1 }
            // n = 5, score = 500
            //   e8????????           |                     
            //   8bc8                 | mov                 dword ptr [esp + 0x40], eax
            //   33d2                 | dec                 eax
            //   8bc7                 | mov                 eax, dword ptr [ecx + 0x48]
            //   f7f1                 | dec                 eax

        $sequence_61 = { ff15???????? 8bf0 c1ee1f 83f601 }
            // n = 4, score = 500
            //   ff15????????         |                     
            //   8bf0                 | dec                 eax
            //   c1ee1f               | mov                 edx, dword ptr [ecx + 0x18]
            //   83f601               | dec                 eax

        $sequence_62 = { 8bf8 58 41 41 }
            // n = 4, score = 400
            //   8bf8                 | jmp                 0x2f
            //   58                   | and                 eax, 0x20
            //   41                   | add                 eax, 0x20
            //   41                   | jmp                 0x3b

        $sequence_63 = { 8bcf e8???????? eb2c 53 8bde e8???????? }
            // n = 6, score = 100
            //   8bcf                 | and                 eax, 0x80000000
            //   e8????????           |                     
            //   eb2c                 | neg                 eax
            //   53                   | sbb                 eax, eax
            //   8bde                 | sbb                 eax, eax
            //   e8????????           |                     

        $sequence_64 = { e8???????? 83c608 4f 75f4 5f }
            // n = 5, score = 100
            //   e8????????           |                     
            //   83c608               | add                 eax, 2
            //   4f                   | jmp                 0xf
            //   75f4                 | and                 eax, 0x80000000
            //   5f                   | neg                 eax

        $sequence_65 = { 12f7 000f 9c 000f 9c 000f 9c }
            // n = 7, score = 100
            //   12f7                 | and                 eax, 0x80000000
            //   000f                 | neg                 eax
            //   9c                   | sbb                 eax, eax
            //   000f                 | and                 eax, 0x20
            //   9c                   | add                 eax, 0x20
            //   000f                 | jmp                 0x40
            //   9c                   | and                 eax, 0x80000000

        $sequence_66 = { 83f908 7229 f3a5 ff2495d0160001 }
            // n = 4, score = 100
            //   83f908               | and                 eax, 0x70
            //   7229                 | add                 eax, 0x10
            //   f3a5                 | jmp                 0x2d
            //   ff2495d0160001       | test                eax, 0x40000000

        $sequence_67 = { 3e3d0d2f389c a6 ac 7df2 140c 46 }
            // n = 6, score = 100
            //   3e3d0d2f389c         | sbb                 eax, eax
            //   a6                   | and                 eax, 7
            //   ac                   | inc                 eax
            //   7df2                 | sbb                 eax, eax
            //   140c                 | and                 eax, 2
            //   46                   | add                 eax, 2

        $sequence_68 = { 7422 889dfbf7ffff e8???????? dd05???????? }
            // n = 4, score = 100
            //   7422                 | add                 eax, 0x20
            //   889dfbf7ffff         | jmp                 0x3b
            //   e8????????           |                     
            //   dd05????????         |                     

        $sequence_69 = { 7616 ff7510 8bc7 e8???????? }
            // n = 4, score = 100
            //   7616                 | and                 eax, 0x70
            //   ff7510               | add                 eax, 0x10
            //   8bc7                 | and                 eax, 0x20
            //   e8????????           |                     

        $sequence_70 = { 897e70 c686c800000043 c6864b01000043 c74668d8f40001 6a0d e8???????? 59 }
            // n = 7, score = 100
            //   897e70               | and                 eax, 0x80000000
            //   c686c800000043       | neg                 eax
            //   c6864b01000043       | sbb                 eax, eax
            //   c74668d8f40001       | and                 eax, 0x80000000
            //   6a0d                 | neg                 eax
            //   e8????????           |                     
            //   59                   | sbb                 eax, eax

    condition:
        7 of them and filesize < 712704
}

rule win_trickbot_w0 {
    meta:
        author = "Marc Salinas @Bondey_m"
        description = "Detects mailsearcher module from Trickbot Trojan"
        reference = "https://www.securityartwork.es/wp-content/uploads/2017/06/Informe_Evoluci%C3%B3n_Trickbot.pdf"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.trickbot"
        malpedia_version = "20170613"
        malpedia_license = "CC BY-NC-SA 4.0"
        malpedia_sharing = "TLP:WHITE"
    strings:
        $str_mails_01 = "mailsearcher"
        $str_mails_02 = "handler"
        $str_mails_03 = "conf"
        $str_mails_04 = "ctl"
        $str_mails_05 = "SetConf"
        $str_mails_06 = "file"
        $str_mails_07 = "needinfo"
        $str_mails_08 = "mailconf"
    condition:
        all of ($str_mails_*)
}

rule win_trickbot_w1 {
    meta:
        description = "Trickbot Socks5 bckconnect module"
        author = "@VK_Intel"
        reference = "Detects the unpacked Trickbot backconnect in memory"
        date = "2017-11-19"
        hash = "f2428d5ff8c93500da92f90154eebdf0"
        source = "http://www.vkremez.com/2017/11/lets-learn-trickbot-socks5-backconnect.html"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.trickbot"
        malpedia_version = "20171214"
        malpedia_license = "CC BY-NC-SA 4.0"
        malpedia_sharing = "TLP:WHITE"
    strings:
        $s0 = "socks5dll.dll" fullword ascii
        $s1 = "auth_login" fullword ascii
        $s2 = "auth_ip" fullword ascii
        $s3 = "connect" fullword ascii
        $s4 = "auth_ip" fullword ascii
        $s5 = "auth_pass" fullword ascii
        $s6 = "thread.entry_event" fullword ascii
        $s7 = "thread.exit_event" fullword ascii
        $s8 = "</moduleconfig>" fullword ascii
        $s9 = "<moduleconfig>" fullword ascii
        $s10 = "<autostart>yes</autostart>" fullword ascii
    condition:
        all of them
}
